// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"wiredemo/service"
	"wiredemo/service/hunt_error"
)

// Injectors from wire.go:

// 返回值：就是我们要创建的类型，wire只知道要创建的类型是什么即可，return返回的是什么不重要
func InitMission(name string) service.Mission {
	player := service.NewPlayer(name)
	monster := service.NewMonster()
	mission := service.NewMission(player, monster)
	return mission
}

// wire.go:

// 错误：
// wire遵循fail-fast的原则，错误必须被处理。如果我们的注入器不返回错误，但构造器返回错误，wire工具会报错！
func InitHunt(name string) (hunt_error.Hunt, error) {
	cat, err := hunt_error.NewCat(name)
	if err != nil {
		return hunt_error.Hunt{}, err
	}

	hunt := hunt_error.NewHunt(cat)
	return hunt, nil
}
